version: '3.8'
services:
  web:
    build: .
    env_file: database.env
    ports:
      - 5000:5000
    volumes:
      - ./backend/:/home/backend/
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    env_file: database.env
    expose:
      - 5432
